[package]
name = "stitch"
version = "0.0.1"
edition = "2021"

[dependencies]
miette = "5.10"
phf = { version = "0.11", features = ["macros"] }
thiserror = "1.0"

[dev-dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
test-generator = "0.3.1"
